### ISSUE TITLE
Build failure on Alpine Linux: undefined reference to 'statfs64' when linking lavinmq v2.4.4

### ISSUE THREAD

**Issue by ionutnechita** [cloudamqp/lavinmq#1292]
Describe the bug
The build process fails during the linking stage with an undefined reference to statfs64 when compiling lavinmq v2.4.4 on Alpine Linux. The compilation completes successfully but fails at the final linking step.
Describe your setup

LavinMQ version: v2.4.4 (tag dd10ea3521f7698ee24cc85f145b2abebdebc65a, commit 3d7f775253617129466fc792b0b7ea0c9d2c325c)
Operating System: Alpine Linux
Compiler: GCC 15.2.0 (x86_64-alpine-linux-musl)
Crystal version: Used in build process
Build environment: Docker container (based on build output showing /tmp/lavinmq-build path)

Build info cannot be retrieved as the build fails before completion.

How to reproduce
Clone the repository: git clone https://github.com/cloudamqp/lavinmq.git -b v2.4.4
Install dependencies: shards install --production
Run make: make all MAKEFLAGS=-j2
Observe the linking error during the final compilation step

Expected behavior
The build should complete successfully and produce the bin/lavinmq executable without linking errors.

Additional context
The error occurs specifically in /tmp/lavinmq-build/src/stdlib/filesystem.cr:88 when trying to link against statfs64. This suggests a compatibility issue with the musl libc used in Alpine Linux, where statfs64 may not be available or may have a different name/signature compared to glibc systems.

Error details:
```
/usr/lib/gcc/x86_64-alpine-linux-musl/15.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: _main.o3.o: in function `info':
/tmp/lavinmq-build/src/stdlib/filesystem.cr:88:(.text+0x33b257): undefined reference to `statfs64'
collect2: error: ld returned 1 exit status
```

**Comment by ionutnechita** [comment]
```
~ # cat 0001-LavinMQ-Fix-Alpine-Linux-build-use-statfs-instead-of.patch 
From 5e8988ef6eb82e246c48fd0407252125ff02806b Mon Sep 17 00:00:00 2001
From: Ionut Nechita <ionut_n2001@yahoo.com>
Date: Sat, 20 Sep 2025 15:29:34 +0300
Subject: [PATCH] [LavinMQ] Fix Alpine Linux build: use statfs instead of
 statfs64 on musl

Description:
 - Alpine Linux uses musl libc which doesn't provide statfs64, only statfs.
   This patch adds conditional compilation to use the appropriate function
   based on the target libc:
   - statfs64 on glibc systems (existing behavior)
   - statfs on musl systems (new behavior for Alpine/musl)

   The filesystem info functionality remains the same across both platforms.

   Fixes build error: undefined reference to 'statfs64'

Change-Id: Ic32d6fa0df2c99c1eafb7068ee12fc216b411b1f
Signed-off-by: Ionut Nechita <ionut_n2001@yahoo.com>
---
 src/stdlib/filesystem.cr | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/src/stdlib/filesystem.cr b/src/stdlib/filesystem.cr
index 58ece3f0..5d89362b 100644
--- a/src/stdlib/filesystem.cr
+++ b/src/stdlib/filesystem.cr
@@ -17,7 +17,11 @@ lib LibC
       spare : StaticArray(Long, 4)
     end
 
-    fun statfs64(file : Char*, buf : Statfs*) : Int
+    {% if flag?(:musl) %}
+      fun statfs(file : Char*, buf : Statfs*) : Int
+    {% else %}
+      fun statfs64(file : Char*, buf : Statfs*) : Int
+    {% end %}
   {% elsif flag?(:darwin) %}
     struct Statfs
       bsize : UInt32
@@ -85,7 +89,7 @@ struct FilesystemInfo
   getter total : UInt64
 end
 
-{% if flag?(:linux) || flag?(:darwin) %}
+{% if (flag?(:linux) && !flag?(:musl)) || flag?(:darwin) %}
   module Filesystem
     def self.info(path)
       statfs = uninitialized LibC::Statfs
@@ -95,7 +99,7 @@ end
       FilesystemInfo.new(statfs)
     end
   end
-{% elsif flag?(:freebsd) %}
+{% elsif flag?(:freebsd) || flag?(:musl) %}
   module Filesystem
     def self.info(path)
       statfs = uninitialized LibC::Statfs
-- 
2.51.0
```

**Comment by kickster97** [comment]
Hi! I have applied your patch in this [PR](https://github.com/cloudamqp/lavinmq/pull/1316), can you check it out and see that it works better for you?

**Comment by ionutnechita** [comment]
Hi Christina - @kickster97 ,

Thank you for your support.

I think this issue has been solved somehow in the meantime, or something happened. Because in the main branch I already see the change made, but on the 2.4.4 tag it does not appear.

Fixed: https://github.com/cloudamqp/lavinmq/blob/main/src/stdlib/filesystem.cr
Not fixed: https://github.com/cloudamqp/lavinmq/blob/v2.4.4/src/stdlib/filesystem.cr

v2.4.4 Release it was published 3-4 weeks ago, but the fix was not backported in v2.4.4.

I think I'll use v2.5.0-rc.1 tag, which already has the fix.
A good day.

**Comment by kickster97** [comment]
@ionutnechita Ah yes, it has.. I must have missed that some how when applying the patch ^^ I have gone ahead and closed that PR. 
 
Ok, sounds good, thanks for your reports :)

**Comment by ionutnechita** [comment]
I have a question Christina - @kickster97. When will version 2.5.0 be created, in what period?

**Comment by kickster97** [comment]
@ionutnechita We have been working on getting 2.5.0-rc.1 stable for a while and it's starting to come together, but we still have some work to merge in order to release 2.5.0 ([see milestone 2.5.0](https://github.com/cloudamqp/lavinmq/milestone/16)). I hope to say that it will be soon, within a week/couple of weeks.

**Comment by ionutnechita** [comment]
> [@ionutnechita](https://github.com/ionutnechita) We have been working on getting 2.5.0-rc.1 stable for a while and it's starting to come together, but we still have some work to merge in order to release 2.5.0 ([see milestone 2.5.0](https://github.com/cloudamqp/lavinmq/milestone/16)). I hope to say that it will be soon, within a week/couple of weeks.

Thank you.
I will use the main branch to see the changes over time.
If I have any more issue or bugs I will let you know.
